### ISSUE TITLE
Task5 PR

### ISSUE THREAD

**Issue by loginov-rocks** [romankurnovskii/store-rss-nodejs-aws-be#1]
Hi!

Could you please open a PR to review the changes, please?

**Comment by romankurnovskii** [comment]
Hello! I've allready merged in master, if any questions write please at discord me if it is possible

**Comment by loginov-rocks** [comment]
> Hello! I've allready merged in master, if any questions write please at discord me if it is possible

Sure, okay then, I take it as you already received your peer review and score :) Good luck!
